<h4>1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written and reusable code modules that provide a set of functionalities or services. These libraries contain functions, classes, and methods
Libraries improve code reusability, modularity, efficienct. It creates a standardisation.

<h4>2. What is the difference between Numpy array and List?

Numpy array is stores homogenous data types while List can store different data types at once.
Array has a contiguous memory allocation while a list has a non contiguous memory allocation

<h4>3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np

In [2]:
a= np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a.shape

(3, 4)

In [4]:
a.size

12

<h4>4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
a[0:1]

array([[1, 2, 3, 4]])

<h4>5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
a[2][3]

12

<h4>6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
a[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

<h4>7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [8]:
import random

b= np.random.rand(3,3)
b

array([[0.126297  , 0.94115874, 0.15288145],
       [0.19278893, 0.24917725, 0.98064942],
       [0.88246825, 0.64454018, 0.48016567]])

<h4>8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand gives random numbers between 0 and 1 while np.random.randn give normalised random numbers which would fit in the bell curve.

<h4> 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
a= np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
c= np.expand_dims(a, axis = 1)
c.shape

(3, 1, 4)

In [11]:
c

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

<h4>10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
a= np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

<h3>11.Consi^er the following matrix: 
<br>Matrix A= [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
<br>Matrix B= [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [14]:

matrix_a = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
matrix_b = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
print (matrix_a,'\n''########''\n',matrix_b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
########
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
#Index wiLe multiplication
matrix_a*matrix_b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [16]:
#Matix multiplication
matrix_c= np.reshape(matrix_b,(4,3))
np.dot(matrix_a,matrix_c)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [17]:
#Add both the matrix
matrix_a+matrix_b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [18]:
#Subtact matix B from matrix A
matrix_b-matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
#Divide Matix B by A
matrix_b/matrix_a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<h4>12. Which function in Numpy can be used to swap the byte order of an array?

In [20]:
#byteswap
matrix_a.byteswap()

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

<h4>13. What is the significance of the np.linalg.inv function?

In [21]:
#it helps us to find the inverse of a matrix

<h4>14. What does the np.reshape function do, and how is it used?

In [23]:
# it is used to chande the shape of an array. While reshaping the size of the matrix should be the same
matrix_c= np.reshape(matrix_b,(4,3))
matrix_c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

<h4>15. What is broa^casting in Numpy?

In [ ]:
#  broadcasting allows you to add them together element-wise as if the smaller array were copied along a new axis to match the shape of the larger array.